language: go
sudo: false
go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...
  
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ./go.test.sh
  - go test -v -covermode=count -coverprofile=coverage.out 
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci 
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
